# Generated by Django 3.1 on 2020-08-12 21:12

from django.db import migrations, models
import post.utils.core


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200813_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=post.utils.core.generate_slug, null=True, unique=True),
        ),
    ]
