# Generated by Django 3.1 on 2020-08-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200813_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
