# Generated by Django 3.1 on 2020-08-15 18:00

from django.db import migrations, models
import django.db.models.deletion
import post.utils.core


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostExtraImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(upload_to=post.utils.core.upload_image_path)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.post')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
    ]
