# Generated by Django 3.1 on 2020-08-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
